schema_version: "1.0"
mcp_name: "Jamaican Law MCP"
jurisdiction: "JM"

sources:
  - name: "Laws of Jamaica"
    authority: "Ministry of Justice, Jamaica"
    official_portal: "https://laws.moj.gov.jm"
    retrieval_method: "PDF_DOWNLOAD + PDFTOTEXT"
    update_frequency: "monthly"
    last_ingested: "2026-02-21"
    license_or_terms:
      type: "Government Publication (informational use)"
      url: "https://laws.moj.gov.jm"
      summary: "Official laws portal; online copies are provided for information."
    coverage:
      scope: "Revised statutes, Acts of Parliament, and revised subsidiary legislation from the Laws of Jamaica portal"
      limitations: "Section-level extraction depends on machine-readable PDF text; scan-only or inaccessible documents are retained as metadata-only entries (documented in data/source/ingestion-report.json)."
    languages:
      - "en"

data_freshness:
  automated_checks: false
  check_frequency: "monthly"
  last_verified: "2026-02-21"
